import type { PanoramaStepDef } from './pipeline-definitions'

export const GOVERNANCE_PANORAMA_STEPS: PanoramaStepDef[] = [
  // 1: 质量门禁与抗熵增质检
  {
    id: 'step_quality_gate',
    nameZh: '质量门禁',
    nameEn: 'Quality Gate',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '用例',
    unitEn: 'cases',
    taskTypes: ['quality_gate', 'benchmark_eval', 'add_resource', 'session_commit'],
    operators: ['QuerySample', 'VectorRetrieve', 'RagasJudge', 'MetricAssert'],
    descriptionZh: '执行 RAGAS 四维抗熵增质检（排布精度、覆盖率、忠实度、相关度），断言检索质量',
    descriptionEn: 'Execute RAGAS 4D anti-entropy evaluation verifying retrieval precision and health',
  },

  // 2-5: 异步托管入库 (Valet Parking) 四工序
  {
    id: 'step_valet_handover',
    nameZh: '快速接管',
    nameEn: 'Fast Handover',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '次',
    unitEn: 'calls',
    taskTypes: ['valet_parking'],
    descriptionZh: '毫秒级接收 Payload 并签发 Ticket，内存与 WAL 双写安全接管',
    descriptionEn: 'Fast payload ingestion and ticket issuance with in-memory WAL durability',
  },
  {
    id: 'step_valet_probe',
    nameZh: '向量探针',
    nameEn: 'Vector Probe',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '探针',
    unitEn: 'probes',
    taskTypes: ['valet_parking'],
    descriptionZh: '多路稠密向量与语义检索探针，计算既有知识库候选集相似度',
    descriptionEn: 'Multi-channel vector and semantic probe calculating similarity against candidates',
  },
  {
    id: 'step_valet_decision',
    nameZh: '准入判定',
    nameEn: 'Admission Check',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '判定',
    unitEn: 'checks',
    taskTypes: ['valet_parking', 'add_resource', 'session_commit'],
    descriptionZh: '执行熵增门禁四态判定 (NOOP去重 / UPDATE升级 / ADD新增 / DLQ隔离)',
    descriptionEn: 'Entropy gatekeeper evaluates 4-way admission verdict (noop/update/add/dlq)',
  },
  {
    id: 'step_valet_parking',
    nameZh: '存储落盘',
    nameEn: 'Storage Persistence',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['valet_parking'],
    descriptionZh: '将新知识原子物理落盘入库，或无缝合并既有节点知识并交付成果物',
    descriptionEn: 'Physically persist knowledge into atomic storage or merge with existing node',
  },

  // 6-7: 托管数据摄取 (Managed Ingestion)
  {
    id: 'step_managed_validate',
    nameZh: '摄取校验',
    nameEn: 'Ingest Validate',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '校验',
    unitEn: 'checks',
    taskTypes: ['managed_ingestion'],
    descriptionZh: '校验托管入库上下文、URI 合规性与元数据规格完整性',
    descriptionEn: 'Validate managed ingestion context, URI schema, and metadata compliance',
  },
  {
    id: 'step_managed_deliver',
    nameZh: '成果交付',
    nameEn: 'Deliverable Ready',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '成果',
    unitEn: 'deliverables',
    taskTypes: ['managed_ingestion'],
    descriptionZh: '构建知识关联拓扑并挂载成果物直达跳转链接',
    descriptionEn: 'Construct knowledge links and attach persistent deliverable URL',
  },

  // 8-10: 用户空间注销 (User Deletion)
  {
    id: 'step_soft_mark',
    nameZh: '空间软标',
    nameEn: 'Soft Mark',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: '空间',
    unitEn: 'spaces',
    taskTypes: ['user_delete', 'user_deletion'],
    descriptionZh: '标记待注销空间元数据，解绑租户关联与路由信息',
    descriptionEn: 'Mark namespace metadata for deletion and unbind tenant routes',
  },
  {
    id: 'step_vector_purge',
    nameZh: '向量抹除',
    nameEn: 'Vector Purge',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '集合',
    unitEn: 'collections',
    taskTypes: ['user_delete', 'user_deletion'],
    descriptionZh: '批量 Drop 向量集合并清除底层向量索引分片',
    descriptionEn: 'Batch drop vector collections and purge vector index shards',
  },
  {
    id: 'step_disk_wipe',
    nameZh: '磁盘擦除',
    nameEn: 'Disk Wipe',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: 'MB',
    unitEn: 'MB',
    taskTypes: ['user_delete', 'user_deletion'],
    descriptionZh: '物理抹除磁盘文件，回收存储配额并重置空间状态',
    descriptionEn: 'Physically wipe disk files, reclaim quotas, and reset space state',
  },
]
