import type { PanoramaStepDef } from './pipeline-definitions'

export const ENTROPY_PANORAMA_STEPS: PanoramaStepDef[] = [
  // 25-28: 记忆流与反思做梦 (Stanford Generative Agents)
  {
    id: 'step_scan_observations',
    nameZh: '观察扫描',
    nameEn: 'Scan Observations',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '条',
    unitEn: 'records',
    taskTypes: ['memory_dream'],
    descriptionZh: '扫描近期低抽象会话流水与原始日志，计算时效衰减与重要性积分',
    descriptionEn: 'Scan raw dialogue streams and calculate recency & importance scores',
  },
  {
    id: 'step_cluster_themes',
    nameZh: '模式聚类',
    nameEn: 'Cluster Themes',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '簇',
    unitEn: 'clusters',
    taskTypes: ['memory_dream'],
    descriptionZh: '对多条琐碎观察进行无监督语义聚类，收敛为核心模式主题',
    descriptionEn: 'Unsupervised clustering of observations into high-level themes',
  },
  {
    id: 'step_distill_insights',
    nameZh: '反思提炼',
    nameEn: 'Distill Insights',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '条',
    unitEn: 'insights',
    taskTypes: ['memory_dream'],
    descriptionZh: '驱动 LLM 深度反思，提炼高阶因果规律、认知洞察与永久准则',
    descriptionEn: 'Invoke LLM for deep reflection and distill high-level causal insights',
  },
  {
    id: 'step_consolidate_master',
    nameZh: '主记忆固化',
    nameEn: 'Consolidate Master',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['memory_dream'],
    descriptionZh: '将提炼洞察作为权威节点写回 Master Memory 并完成向量入脑',
    descriptionEn: 'Write insight nodes into Master Memory and embed into vector index',
  },

  // 29-32: 分层内存与压缩淘汰 (MemGPT / Letta)
  {
    id: 'step_evaluate_tiers',
    nameZh: '分层体检',
    nameEn: 'Evaluate Tiers',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '条',
    unitEn: 'records',
    taskTypes: ['memory_compaction'],
    descriptionZh: '依据 access_count 与最后访问时间，执行 Hot/Warm/Cold 自动分层',
    descriptionEn: 'Evaluate access frequency and recency for Hot/Warm/Cold tiering',
  },
  {
    id: 'step_cosine_deduplication',
    nameZh: '余弦去重',
    nameEn: 'Cosine Dedup',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '对',
    unitEn: 'pairs',
    taskTypes: ['memory_compaction'],
    descriptionZh: '余弦相似度高阈值 (>0.92) 重复项检测与淘汰标记',
    descriptionEn: 'Cosine similarity high-threshold (>0.92) redundancy detection',
  },
  {
    id: 'step_prune_and_archive',
    nameZh: '剪枝归档',
    nameEn: 'Prune & Archive',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Space Purge Engine',
    unitZh: '条',
    unitEn: 'items',
    taskTypes: ['memory_compaction'],
    descriptionZh: '按艾宾浩斯半衰期淘汰低价值碎屑，超额记忆归档至冷存',
    descriptionEn: 'Prune decayed fragments and archive overflow memories to cold storage',
  },
  {
    id: 'step_rebalance_index',
    nameZh: '索引重平衡',
    nameEn: 'Rebalance Index',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '簇心',
    unitEn: 'centroids',
    taskTypes: ['memory_compaction'],
    descriptionZh: '重新计算向量聚类中心，消除空洞与向量空间拥挤',
    descriptionEn: 'Recompute vector centroids to eliminate fragmentation and crowding',
  },

  // 33-36: 增量事实与四态流转 (Mem0 / AutoGen)
  {
    id: 'step_extract_atomic_facts',
    nameZh: '原子事实抽取',
    nameEn: 'Extract Facts',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '事实',
    unitEn: 'facts',
    taskTypes: ['fact_mutation'],
    descriptionZh: '将非结构化文档或对话拆解为高精度独立原子事实断言',
    descriptionEn: 'Decompose source text into atomic independent factual assertions',
  },
  {
    id: 'step_semantic_conflict_check',
    nameZh: '冲突检测',
    nameEn: 'Conflict Check',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '断言',
    unitEn: 'assertions',
    taskTypes: ['fact_mutation'],
    descriptionZh: '与现有事实图谱对比，检测语义重叠、演变与事实自相矛盾',
    descriptionEn: 'Compare against existing graph to detect overlaps and contradictions',
  },
  {
    id: 'step_execute_4way_mutation',
    nameZh: '四态流转',
    nameEn: '4-Way Mutation',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '动作',
    unitEn: 'actions',
    taskTypes: ['fact_mutation'],
    descriptionZh: '执行 ADD(增)/UPDATE(变)/DELETE(废)/NOOP(略) 四态决策分流',
    descriptionEn: 'Execute ADD/UPDATE/DELETE/NOOP 4-way mutation routing at ingestion gate',
  },
  {
    id: 'step_commit_knowledge_graph',
    nameZh: '图谱原子提交',
    nameEn: 'Commit Graph',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '事实',
    unitEn: 'facts',
    taskTypes: ['fact_mutation'],
    descriptionZh: '将事实变更原子提交至图谱与向量索引，入口阻断信息熵增',
    descriptionEn: 'Atomically commit fact changes to graph and vector index',
  },

  // 37-40: 时态图谱与实体浓缩 (Zep)
  {
    id: 'step_extract_entities_relations',
    nameZh: '实体关系抽取',
    nameEn: 'Entity Relations',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '三元组',
    unitEn: 'triples',
    taskTypes: ['entity_summarization'],
    descriptionZh: '提取实体、属性、事件与因果拓扑三元组',
    descriptionEn: 'Extract entity-attribute-event causal topology triples',
  },
  {
    id: 'step_temporal_timeline_ordering',
    nameZh: '时序排序',
    nameEn: 'Timeline Ordering',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '事件',
    unitEn: 'events',
    taskTypes: ['entity_summarization'],
    descriptionZh: '沿时间轴对实体变更事件建立有序版本演进链',
    descriptionEn: 'Order entity evolution events along chronological timeline',
  },
  {
    id: 'step_merge_temporal_contradictions',
    nameZh: '时序矛盾消解',
    nameEn: 'Resolve Contradictions',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '冲突',
    unitEn: 'conflicts',
    taskTypes: ['entity_summarization'],
    descriptionZh: '消解历史先后冲突，提纯当前时刻权威事实 (Current Truth)',
    descriptionEn: 'Resolve temporal contradictions and distill current authoritative state',
  },
  {
    id: 'step_update_entity_index',
    nameZh: '实体浓缩更新',
    nameEn: 'Update Entity SSOT',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '实体',
    unitEn: 'entities',
    taskTypes: ['entity_summarization'],
    descriptionZh: '更新实体单一真相源 (SSOT) 浓缩文档与关联向量',
    descriptionEn: 'Update entity single source of truth summary document and vectors',
  },

  // 41-44: 四层治理与同主题合并 (Home Project Baseline)
  {
    id: 'step_tier_diagnosis',
    nameZh: '四层全息诊断',
    nameEn: 'Four-Tier Diagnosis',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '维度',
    unitEn: 'tiers',
    taskTypes: ['four_tier_governance'],
    descriptionZh: '数量层、质量层、结构层、查询层全息健康度体检',
    descriptionEn: 'Diagnosis across quantity, quality, structure, and query tiers',
  },
  {
    id: 'step_topic_grouping',
    nameZh: '同主题聚类',
    nameEn: 'Topic Grouping',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '主题',
    unitEn: 'topics',
    taskTypes: ['four_tier_governance'],
    descriptionZh: '将散落在不同文档和历史会话中的同主题零散笔记聚类合并',
    descriptionEn: 'Group scattered topic fragments across documents and conversations',
  },
  {
    id: 'step_llm_topic_synthesis',
    nameZh: '主题深度归纳',
    nameEn: 'Topic Synthesis',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '篇',
    unitEn: 'docs',
    taskTypes: ['four_tier_governance'],
    descriptionZh: '驱动 LLM 深度整合同主题笔记，剔除重复，提纯为结构化统一纲要',
    descriptionEn: 'Invoke LLM to synthesize topic notes into a clean structural outline',
  },
  {
    id: 'step_writeback_and_cleanup',
    nameZh: '纲要写回与清理',
    nameEn: 'Writeback & Clean',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['four_tier_governance'],
    descriptionZh: '结构化合并产物落盘写回，重构向量并软删除分散过时碎片',
    descriptionEn: 'Persist consolidated outline, reindex vectors, soft-delete fragments',
  },
]
