import type { PanoramaStepDef } from './pipeline-definitions'

export const INFRA_PANORAMA_STEPS: PanoramaStepDef[] = [
  // 1-5: 资源处理相关
  {
    id: 'step_ingestion',
    nameZh: '资源入库',
    nameEn: 'Resource Ingestion',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '文件',
    unitEn: 'files',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '校验 SHA256，在 AGFS 中创建物理 Inode 节点并落盘',
    descriptionEn: 'Verify SHA256, create physical Inode in AGFS and persist to disk',
  },
  {
    id: 'step_parse',
    nameZh: '文档解析',
    nameEn: 'Document Parsing',
    engineKey: 'ExternalParse',
    engineNameZh: '文档解析',
    engineNameEn: 'Document Parsing Engine',
    unitZh: '页 / 篇',
    unitEn: 'pages / docs',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '多格式解析引擎（MarkItDown/PDF/Docx/HTML）段落结构化',
    descriptionEn: 'Multi-format parser structuring Markdown, PDF, Docx, HTML',
  },
  {
    id: 'step_semantic',
    nameZh: '语义提取',
    nameEn: 'Semantic Extraction',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '调用 LLM/VLM 大模型脑力提取 L0/L1 概念与分层摘要',
    descriptionEn: 'Invoke LLM/VLM to extract L0/L1 concepts and hierarchical summaries',
  },
  {
    id: 'step_embedding',
    nameZh: '向量建库',
    nameEn: 'Vector Embedding',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['add_resource', 'add_skill', 'connector_import'],
    descriptionZh: '文本切片分块，GPU 并发计算稠密向量并存入 VikingDB',
    descriptionEn: 'Text chunking, compute dense vectors on GPU and insert into VikingDB',
  },
  {
    id: 'step_memory_linking',
    nameZh: '记忆关联',
    nameEn: 'Memory Linking',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '关联',
    unitEn: 'links',
    taskTypes: ['add_resource'],
    descriptionZh: '跨资源实体网状关系提炼，构建知识图谱与全局拓扑记忆关联',
    descriptionEn: 'Cross-resource entity relation distillation, building knowledge graph & memory topology links',
  },

  // 6-7: 技能导入相关
  {
    id: 'step_discovery',
    nameZh: '目录扫描',
    nameEn: 'Directory Discovery',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '目录',
    unitEn: 'dirs',
    taskTypes: ['add_skill'],
    descriptionZh: '遍历扫描 skills/ 插件目录结构与元数据文件',
    descriptionEn: 'Traverse and scan skills/ plugin directory structure and metadata',
  },
  {
    id: 'step_validation',
    nameZh: '规范校验',
    nameEn: 'Spec Validation',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '技能',
    unitEn: 'skills',
    taskTypes: ['add_skill'],
    descriptionZh: '校验 SKILL.md 的 YAML 头部合规性与执行指令完整性',
    descriptionEn: 'Validate YAML frontmatter compliance and action completeness in SKILL.md',
  },

  // 8-10: 会话归档相关
  {
    id: 'step_serialization',
    nameZh: '会话归档',
    nameEn: 'Context Serialization',
    engineKey: 'SessionCommit',
    engineNameZh: '会话提纯',
    engineNameEn: 'Session Distillation Engine',
    unitZh: '轮',
    unitEn: 'turns',
    taskTypes: ['session_commit'],
    descriptionZh: '冻结活动会话上下文，打包生成时序只读归档片段',
    descriptionEn: 'Freeze active session context and package read-only archive slices',
  },
  {
    id: 'step_distillation',
    nameZh: '记忆萃取',
    nameEn: 'Insight Distillation',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '条',
    unitEn: 'lessons',
    taskTypes: ['session_commit'],
    descriptionZh: '大模型提炼核心规则演进教训、代码偏好与实体因果',
    descriptionEn: 'LLM extracts core rule evolutions, code preferences, and entity causality',
  },
  {
    id: 'step_persistence',
    nameZh: '长期沉淀',
    nameEn: 'Long-term Memory',
    engineKey: 'SessionCommit',
    engineNameZh: '会话提纯',
    engineNameEn: 'Session Distillation Engine',
    unitZh: '项',
    unitEn: 'insights',
    taskTypes: ['session_commit'],
    descriptionZh: '将提纯经验写入 master_memory/ 与全局演进知识库',
    descriptionEn: 'Persist distilled lessons to master_memory/ and global knowledge base',
  },

  // 11-13: 索引重建相关
  {
    id: 'step_scan',
    nameZh: '全量扫描',
    nameEn: 'Full Scan',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'inodes',
    taskTypes: ['admin_reindex'],
    descriptionZh: '遍历扫描所有已注册资源与主记忆节点 Inode',
    descriptionEn: 'Traverse and scan all registered resources and memory node Inodes',
  },
  {
    id: 'step_rebuild_semantic',
    nameZh: '语义重构',
    nameEn: 'Semantic Rebuild',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['admin_reindex'],
    descriptionZh: '重新生成 L0/L1 分层结构与实体语义关系树',
    descriptionEn: 'Regenerate L0/L1 hierarchical structures and entity trees',
  },
  {
    id: 'step_rebuild_vectors',
    nameZh: '向量重构',
    nameEn: 'Vector Rebuild',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['admin_reindex'],
    descriptionZh: '全量清空旧向量并重新计算所有分块的高维嵌入',
    descriptionEn: 'Purge stale vectors and recompute high-dimensional embeddings',
  },

  // 14-15: 快照还原重索引
  {
    id: 'step_inode_restore',
    nameZh: '节点还原',
    nameEn: 'Inode Restore',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'inodes',
    taskTypes: ['snapshot_restore_reindex'],
    descriptionZh: '重建快照中的 Inode 索引节点与属性元数据',
    descriptionEn: 'Rebuild Inode index nodes and attribute metadata from snapshot',
  },
  {
    id: 'step_incremental_vector',
    nameZh: '增量向量',
    nameEn: 'Incremental Embedding',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['snapshot_restore_reindex'],
    descriptionZh: '仅对差异变更的切片进行增量向量计算与补齐',
    descriptionEn: 'Compute incremental vector embeddings only for modified chunks',
  },

  // 16-17: 连接器导入
  {
    id: 'step_auth',
    nameZh: '连接鉴权',
    nameEn: 'Connector Auth',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '连接',
    unitEn: 'connections',
    taskTypes: ['connector_import'],
    descriptionZh: '校验外部源 Token 与凭证',
    descriptionEn: 'Validate external source tokens',
  },
  {
    id: 'step_fetch',
    nameZh: '资源拉取',
    nameEn: 'Remote Fetch',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '篇',
    unitEn: 'docs',
    taskTypes: ['connector_import'],
    descriptionZh: '从外部 API 批量拉取文档流与附件并缓冲至暂存区',
    descriptionEn: 'Batch fetch document streams and attachments from external APIs',
  },

  // 18-20: 旧数据迁移
  {
    id: 'step_read',
    nameZh: '数据读取',
    nameEn: 'Legacy Read',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '条',
    unitEn: 'records',
    taskTypes: ['legacy_migration'],
    descriptionZh: '兼容性加载旧版 V1/V2 数据库与历史元数据存储',
    descriptionEn: 'Backward-compatible loading of legacy V1/V2 database records',
  },
  {
    id: 'step_transform',
    nameZh: '格式转换',
    nameEn: 'Schema Transform',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '项',
    unitEn: 'items',
    taskTypes: ['legacy_migration'],
    descriptionZh: '将旧版 Schema 转换为 OpenViking 标准化 AGFS Schema',
    descriptionEn: 'Transform legacy schema into OpenViking standard AGFS schema',
  },
  {
    id: 'step_agfs_write',
    nameZh: '存储落盘',
    nameEn: 'Storage Persist',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'inodes',
    taskTypes: ['legacy_migration'],
    descriptionZh: '把迁移后的结构化数据原子写入 AGFS 文件系统并落盘',
    descriptionEn: 'Atomically write migrated structured data into AGFS tree',
  },

  // 21-23: 旧数据清理
  {
    id: 'step_traverse',
    nameZh: '图谱遍历',
    nameEn: 'Graph Traversal',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '实体',
    unitEn: 'entities',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '深度遍历知识图谱关联，标记所有活跃与失效引用链',
    descriptionEn: 'Deep traverse knowledge graph to mark active and stale references',
  },
  {
    id: 'step_gc',
    nameZh: '碎片回收',
    nameEn: 'Garbage Collection',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: '项',
    unitEn: 'items',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '执行垃圾回收 (GC) 算法，清除断链悬空实体与无效切片',
    descriptionEn: 'Garbage collection to purge dangling entities and stale chunks',
  },
  {
    id: 'step_free',
    nameZh: '空间释放',
    nameEn: 'Space Release',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: 'MB / 字节',
    unitEn: 'MB / bytes',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '物理释放磁盘占用，整理存储空间并更新配额',
    descriptionEn: 'Physically release disk storage and update namespace quotas',
  },
]
