import type { PanoramaStepDef } from './pipeline-definitions'

export const CORE_PANORAMA_STEPS: PanoramaStepDef[] = [
  // 1-4: 资源处理相关
  {
    id: 'step_ingestion',
    nameZh: '资源入库',
    nameEn: 'Resource Ingestion',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '文件',
    unitEn: 'files',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '校验 SHA256，在 AGFS 中创建物理 Inode 节点并落盘',
    descriptionEn: 'Verify SHA256, create physical Inode in AGFS and persist to disk',
  },
  {
    id: 'step_parse',
    nameZh: '文档解析',
    nameEn: 'Document Parsing',
    engineKey: 'ExternalParse',
    engineNameZh: '文档解析',
    engineNameEn: 'Document Parsing Engine',
    unitZh: '页 / 篇',
    unitEn: 'pages / docs',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '多格式解析引擎（MarkItDown/PDF/Docx/HTML）段落结构化',
    descriptionEn: 'Multi-format parser structuring Markdown, PDF, Docx, HTML',
  },
  {
    id: 'step_semantic',
    nameZh: '语义提取',
    nameEn: 'Semantic Extraction',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '调用 LLM/VLM 大模型脑力提取 L0/L1 概念与分层摘要',
    descriptionEn: 'Invoke LLM/VLM to extract L0/L1 concepts and hierarchical summaries',
  },
  {
    id: 'step_embedding',
    nameZh: '向量建库',
    nameEn: 'Vector Embedding',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['add_resource', 'add_skill', 'connector_import'],
    descriptionZh: '文本切片分块，GPU 并发计算稠密向量并存入 VikingDB',
    descriptionEn: 'Text chunking, compute dense vectors on GPU and insert into VikingDB',
  },
  {
    id: 'step_memory_linking',
    nameZh: '记忆关联',
    nameEn: 'Memory Linking',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '关联',
    unitEn: 'links',
    taskTypes: ['add_resource'],
    descriptionZh: '跨资源实体网状关系提炼，构建知识图谱与全局拓扑记忆关联',
    descriptionEn: 'Cross-resource entity relation distillation, building knowledge graph & memory topology links',
  },

  // 5-6: 技能导入相关
  {
    id: 'step_discovery',
    nameZh: '目录扫描',
    nameEn: 'Directory Discovery',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '目录',
    unitEn: 'dirs',
    taskTypes: ['add_skill'],
    descriptionZh: '遍历扫描 skills/ 插件目录结构与元数据文件',
    descriptionEn: 'Traverse and scan skills/ plugin directory structure and metadata',
  },
  {
    id: 'step_validation',
    nameZh: '规范校验',
    nameEn: 'Spec Validation',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '技能',
    unitEn: 'skills',
    taskTypes: ['add_skill'],
    descriptionZh: '校验 SKILL.md 的 YAML 头部合规性与执行指令完整性',
    descriptionEn: 'Validate YAML frontmatter compliance and action completeness in SKILL.md',
  },

  // 7-9: 会话归档相关
  {
    id: 'step_archival',
    nameZh: '对话归档',
    nameEn: 'Dialogue Archival',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '轮',
    unitEn: 'turns',
    taskTypes: ['session_commit'],
    descriptionZh: '提取 Agent 对话多轮历史，序列化上下文与消息流水',
    descriptionEn: 'Extract multi-turn dialogue history, serialize context and messages',
  },
  {
    id: 'step_lessons',
    nameZh: '经验萃取',
    nameEn: 'Lesson Extraction',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '条经验',
    unitEn: 'lessons',
    taskTypes: ['session_commit'],
    descriptionZh: '提炼对话中的工程教训、决策偏好并沉淀为记忆 Lessons',
    descriptionEn: 'Distill engineering lessons and decision preferences into memory lessons',
  },
  {
    id: 'step_snapshot',
    nameZh: '快照提交',
    nameEn: 'Snapshot Commit',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '快照',
    unitEn: 'commits',
    taskTypes: ['session_commit'],
    descriptionZh: '生成全局版本快照 Commit，确保跨会话持久化与可回滚',
    descriptionEn: 'Generate global snapshot commit ensuring persistence and rollback',
  },

  // 10-12: 全局索引重建
  {
    id: 'step_scan',
    nameZh: '语义提炼',
    nameEn: 'Semantic Generation',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['admin_reindex'],
    descriptionZh: '递归遍历并调用 LLM 生成知识库所有文件与目录的语义摘要 (.abstract.md / .overview.md)',
    descriptionEn: 'Recursively traverse and generate semantic summaries for all nodes',
  },
  {
    id: 'step_reconstruction',
    nameZh: '切片重构',
    nameEn: 'Chunk Reconstruction',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['admin_reindex'],
    descriptionZh: '按照最新 Embedding 模型超参数重新切块并计算全量向量',
    descriptionEn: 'Re-chunk and compute full vector embeddings using latest parameters',
  },
  {
    id: 'step_pruning',
    nameZh: '悬空修剪',
    nameEn: 'Orphan Pruning',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['admin_reindex'],
    descriptionZh: '清理已删除或断开关联的悬空切片与历史悬空记录（仅在指定修剪模式或检测到孤儿碎片时按需触发）',
    descriptionEn: 'Clean up orphaned chunks and dangling historical records',
  },

  // 13-15: 快照恢复重构
  {
    id: 'step_rollback',
    nameZh: '快照回滚',
    nameEn: 'Snapshot Rollback',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '快照',
    unitEn: 'commits',
    taskTypes: ['snapshot_restore_reindex'],
    descriptionZh: '定位历史快照 Tag，安全回滚 AGFS 目录树状态',
    descriptionEn: 'Locate historical snapshot tag and safely rollback AGFS directory state',
  },
  {
    id: 'step_inodes',
    nameZh: '节点还原',
    nameEn: 'Inode Restoration',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'inodes',
    taskTypes: ['snapshot_restore_reindex'],
    descriptionZh: '重建快照中的 Inode 索引节点与属性元数据',
    descriptionEn: 'Rebuild Inode index nodes and attribute metadata from snapshot',
  },
  {
    id: 'step_incremental_vector',
    nameZh: '增量向量',
    nameEn: 'Incremental Embedding',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['snapshot_restore_reindex'],
    descriptionZh: '仅对差异变更的切片进行增量向量计算与补齐',
    descriptionEn: 'Compute incremental vector embeddings only for modified chunks',
  },

  // 16-17: 连接器导入
  {
    id: 'step_auth',
    nameZh: '连接鉴权',
    nameEn: 'Connector Auth',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '连接',
    unitEn: 'connections',
    taskTypes: ['connector_import'],
    descriptionZh: '校验飞书/Notion/GitHub/WebDAV 等外部源 Token 与凭证',
    descriptionEn: 'Validate external source tokens for Feishu, Notion, GitHub, WebDAV',
  },
  {
    id: 'step_fetch',
    nameZh: '资源拉取',
    nameEn: 'Remote Fetch',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '篇',
    unitEn: 'docs',
    taskTypes: ['connector_import'],
    descriptionZh: '从外部 API 批量拉取文档流与附件并缓冲至暂存区',
    descriptionEn: 'Batch fetch document streams and attachments from external APIs',
  },

  // 18-20: 旧数据迁移
  {
    id: 'step_read',
    nameZh: '数据读取',
    nameEn: 'Legacy Read',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '条',
    unitEn: 'records',
    taskTypes: ['legacy_migration'],
    descriptionZh: '兼容性加载旧版 V1/V2 数据库与历史元数据存储',
    descriptionEn: 'Backward-compatible loading of legacy V1/V2 database records',
  },
  {
    id: 'step_transform',
    nameZh: '格式转换',
    nameEn: 'Schema Transform',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '项',
    unitEn: 'items',
    taskTypes: ['legacy_migration'],
    descriptionZh: '将旧版 Schema 转换为 OpenViking 标准化 AGFS Schema',
    descriptionEn: 'Transform legacy schema into OpenViking standard AGFS schema',
  },
  {
    id: 'step_agfs_write',
    nameZh: '存储落盘',
    nameEn: 'Storage Persist',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'inodes',
    taskTypes: ['legacy_migration'],
    descriptionZh: '把迁移后的结构化数据原子写入 AGFS 文件系统并落盘',
    descriptionEn: 'Atomically write migrated structured data into AGFS tree',
  },

  // 21-23: 旧数据清理
  {
    id: 'step_traverse',
    nameZh: '图谱遍历',
    nameEn: 'Graph Traversal',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '实体',
    unitEn: 'entities',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '深度遍历知识图谱关联，标记所有活跃与失效引用链',
    descriptionEn: 'Deep traverse knowledge graph to mark active and stale references',
  },
  {
    id: 'step_gc',
    nameZh: '碎片回收',
    nameEn: 'Garbage Collection',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: '项',
    unitEn: 'items',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '执行垃圾回收 (GC) 算法，清除断链悬空实体与无效切片',
    descriptionEn: 'Garbage collection to purge dangling entities and stale chunks',
  },
  {
    id: 'step_free',
    nameZh: '空间释放',
    nameEn: 'Space Release',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: 'MB / 字节',
    unitEn: 'MB / bytes',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '物理释放磁盘占用，整理存储空间并更新配额',
    descriptionEn: 'Physically release disk storage and update namespace quotas',
  },

  // 24: 质量门禁与抗熵增质检
  {
    id: 'step_quality_gate',
    nameZh: '质量门禁',
    nameEn: 'Quality Gate',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '用例',
    unitEn: 'cases',
    taskTypes: ['quality_gate', 'benchmark_eval'],
    operators: ['QuerySample', 'VectorRetrieve', 'RagasJudge', 'MetricAssert'],
    descriptionZh: '执行 RAGAS 四维抗熵增质检（排布精度、覆盖率、忠实度、相关度），断言检索质量',
    descriptionEn: 'Execute RAGAS 4D anti-entropy evaluation verifying retrieval precision and health',
  },
]
