import type { PanoramaStepDef } from './pipeline-definitions'

export const GOVERNANCE_PANORAMA_STEPS: PanoramaStepDef[] = [
  // 1: 熵增防御与去重演化 (全车间通用后门)
  {
    id: 'step_quality_gate',
    nameZh: '熵增防御',
    nameEn: 'Entropy Defense',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '用例',
    unitEn: 'cases',
    taskTypes: ['quality_gate', 'benchmark_eval', 'valet_parking', 'add_resource', 'session_commit'],
    operators: ['QuerySample', 'VectorRetrieve', 'RagasJudge', 'MetricAssert'],
    descriptionZh: '执行向量查重、指纹比对与四态裁决 (NOOP去重 / UPDATE演进 / ADD新增 / DLQ隔离)，阻断语义熵增',
    descriptionEn: 'Entropy defense evaluating vector duplicate checks and 4-way mutation against entropy increase',
  },

  // 2-5: 异步托管入库 (Valet Parking / 原子入库) 四工序
  {
    id: 'step_valet_handover',
    nameZh: '轻量准入',
    nameEn: 'Lightweight Admission',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '次',
    unitEn: 'calls',
    taskTypes: ['valet_parking'],
    descriptionZh: '毫秒级接收 Payload 并签发 Ticket，通用轻量快轨入库准入',
    descriptionEn: 'Fast payload ingestion and ticket issuance with lightweight admission',
  },
  {
    id: 'step_session_admission',
    nameZh: '会话准入',
    nameEn: 'Session Admission',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '会话',
    unitEn: 'sessions',
    taskTypes: ['session_commit'],
    descriptionZh: '会话边界切分、对话轮次计算与不可变原始归档快照准入',
    descriptionEn: 'Session boundary slicing, turn budget calculation, and immutable archive admission',
  },
  {
    id: 'step_resource_admission',
    nameZh: '资源准入',
    nameEn: 'Resource Admission',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '文件',
    unitEn: 'files',
    taskTypes: ['add_resource'],
    descriptionZh: '校验源文件合法性、分配 Inode 与源端输入准入',
    descriptionEn: 'Validate source payload schema, allocate inode, and ingress admission',
  },
  {
    id: 'step_valet_probe',
    nameZh: '向量探针',
    nameEn: 'Vector Probe',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '探针',
    unitEn: 'probes',
    taskTypes: ['valet_parking'],
    descriptionZh: '多路稠密向量与语义检索探针，计算既有知识库候选集相似度',
    descriptionEn: 'Multi-channel vector and semantic probe calculating similarity against candidates',
  },
  {
    id: 'step_valet_decision',
    nameZh: '轻量准入',
    nameEn: 'Lightweight Admission',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '判定',
    unitEn: 'checks',
    taskTypes: ['valet_parking', 'add_resource', 'session_commit'],
    descriptionZh: '执行熵增门禁四态判定 (NOOP去重 / UPDATE升级 / ADD新增 / DLQ隔离)',
    descriptionEn: 'Entropy gatekeeper evaluates 4-way admission verdict (noop/update/add/dlq)',
  },
  {
    id: 'step_valet_parking',
    nameZh: '存储落盘',
    nameEn: 'Storage Persistence',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['valet_parking'],
    descriptionZh: '将新知识原子物理落盘入库，或无缝合并既有节点知识并交付成果物',
    descriptionEn: 'Physically persist knowledge into atomic storage or merge with existing node',
  },

  // 6-7: 托管数据摄取 (Managed Ingestion)
  {
    id: 'step_managed_validate',
    nameZh: '摄取校验',
    nameEn: 'Ingest Validate',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '校验',
    unitEn: 'checks',
    taskTypes: ['managed_ingestion'],
    descriptionZh: '校验托管入库上下文、URI 合规性与元数据规格完整性',
    descriptionEn: 'Validate managed ingestion context, URI schema, and metadata compliance',
  },
  {
    id: 'step_managed_deliver',
    nameZh: '成果交付',
    nameEn: 'Deliverable Ready',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '成果',
    unitEn: 'deliverables',
    taskTypes: ['managed_ingestion'],
    descriptionZh: '构建知识关联拓扑并挂载成果物直达跳转链接',
    descriptionEn: 'Construct knowledge links and attach persistent deliverable URL',
  },

  // 8-10: 用户空间注销 (User Deletion)
  {
    id: 'step_soft_mark',
    nameZh: '空间软标',
    nameEn: 'Soft Mark',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: '空间',
    unitEn: 'spaces',
    taskTypes: ['user_delete', 'user_deletion'],
    descriptionZh: '标记待注销空间元数据，解绑租户关联与路由信息',
    descriptionEn: 'Mark namespace metadata for deletion and unbind tenant routes',
  },
  {
    id: 'step_vector_purge',
    nameZh: '向量抹除',
    nameEn: 'Vector Purge',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '集合',
    unitEn: 'collections',
    taskTypes: ['user_delete', 'user_deletion'],
    descriptionZh: '批量 Drop 向量集合并清除底层向量索引分片',
    descriptionEn: 'Batch drop vector collections and purge vector index shards',
  },
  {
    id: 'step_disk_wipe',
    nameZh: '磁盘擦除',
    nameEn: 'Disk Wipe',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: 'MB',
    unitEn: 'MB',
    taskTypes: ['user_delete', 'user_deletion'],
    descriptionZh: '物理抹除磁盘文件，回收存储配额并重置空间状态',
    descriptionEn: 'Physically wipe disk files, reclaim quotas, and reset space state',
  },
]
