export interface PanoramaStepDef {
  id: string
  nameZh: string
  nameEn: string
  engineKey:
    | 'AddResource'
    | 'ExternalParse'
    | 'Semantic'
    | 'Semantic-Nodes'
    | 'Embedding'
    | 'SessionCommit'
    | 'UserDeletion'
  engineNameZh: string
  engineNameEn: string
  unitZh: string
  unitEn: string
  taskTypes: string[]
  operators?: string[]
  descriptionZh: string
  descriptionEn: string
}

export interface EngineDef {
  key:
    | 'AddResource'
    | 'ExternalParse'
    | 'Semantic'
    | 'Semantic-Nodes'
    | 'Embedding'
    | 'SessionCommit'
    | 'UserDeletion'
  nameZh: string
  nameEn: string
  descZh: string
  descEn: string
}

export const ENGINE_DEFINITIONS: EngineDef[] = [
  {
    key: 'AddResource',
    nameZh: '资源入库',
    nameEn: 'Resource Ingestion',
    descZh: '负责文件系统落盘、SHA256 校验、Inode 创建与外部源下载拉取',
    descEn: 'AGFS disk writes, SHA256 hashing, Inode creation, connector fetch',
  },
  {
    key: 'ExternalParse',
    nameZh: '文档解析',
    nameEn: 'Document Parsing',
    descZh: '多格式解析器（PDF, Markdown, HTML, 代码）段落结构化与分页',
    descEn: 'Multi-format parser for PDF, Markdown, HTML, code structuring',
  },
  {
    key: 'Semantic',
    nameZh: '语义分析',
    nameEn: 'Semantic Extraction & Gate',
    descZh: '调用大模型提取概念概要、萃取经验记忆并执行抗熵增质检四大算子',
    descEn: 'Invoke LLM/VLM for concepts, lesson extraction, and quality gate operators',
  },
  {
    key: 'Embedding',
    nameZh: '向量计算',
    nameEn: 'Vector Embedding',
    descZh: '文本切片分块，GPU 并发计算稠密向量并写入 VikingDB 向量库',
    descEn: 'Chunk text, GPU vector computation, insert into VikingDB',
  },
  {
    key: 'SessionCommit',
    nameZh: '会话归档',
    nameEn: 'Session Archival',
    descZh: '处理多轮对话流水、萃取长程经验 Lesson 并打上 AGFS 快照',
    descEn: 'Process multi-turn dialogue, extract lessons, commit AGFS snapshot',
  },
  {
    key: 'UserDeletion',
    nameZh: '空间注销',
    nameEn: 'Space Purge',
    descZh: '租户空间解绑、向量集合批量 Drop 擦除与无主孤儿垃圾回收',
    descEn: 'Namespace unbinding, vector drop, disk erase and orphan GC',
  },
  {
    key: 'Semantic-Nodes',
    nameZh: '语义拓扑',
    nameEn: 'Semantic Topology',
    descZh: '知识图谱关联遍历与跨资源实体网状关联构建',
    descEn: 'Knowledge graph traversal and cross-resource relation building',
  },
]

export const ALL_PANORAMA_STEPS: PanoramaStepDef[] = [
  // 1-4: 资源处理相关
  {
    id: 'step_ingestion',
    nameZh: '资源入库',
    nameEn: 'Resource Ingestion',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '文件',
    unitEn: 'files',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '校验 SHA256，在 AGFS 中创建物理 Inode 节点并落盘',
    descriptionEn: 'Verify SHA256, create physical Inode in AGFS and persist to disk',
  },
  {
    id: 'step_parse',
    nameZh: '文档解析',
    nameEn: 'Document Parsing',
    engineKey: 'ExternalParse',
    engineNameZh: '文档解析',
    engineNameEn: 'Document Parsing Engine',
    unitZh: '页 / 篇',
    unitEn: 'pages / docs',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '多格式解析引擎（MarkItDown/PDF/Docx/HTML）段落结构化',
    descriptionEn: 'Multi-format parser structuring Markdown, PDF, Docx, HTML',
  },
  {
    id: 'step_semantic',
    nameZh: '语义提取',
    nameEn: 'Semantic Extraction',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['add_resource', 'connector_import'],
    descriptionZh: '调用 LLM/VLM 大模型脑力提取 L0/L1 概念与分层摘要',
    descriptionEn: 'Invoke LLM/VLM to extract L0/L1 concepts and hierarchical summaries',
  },
  {
    id: 'step_embedding',
    nameZh: '向量建库',
    nameEn: 'Vector Embedding',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['add_resource', 'add_skill', 'connector_import'],
    descriptionZh: '文本切片分块，GPU 并发计算稠密向量并存入 VikingDB',
    descriptionEn: 'Text chunking, compute dense vectors on GPU and insert into VikingDB',
  },
  {
    id: 'step_memory_linking',
    nameZh: '记忆关联',
    nameEn: 'Memory Linking',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '关联',
    unitEn: 'links',
    taskTypes: ['add_resource'],
    descriptionZh: '跨资源实体网状关系提炼，构建知识图谱与全局拓扑记忆关联',
    descriptionEn: 'Cross-resource entity relation distillation, building knowledge graph & memory topology links',
  },

  // 5-6: 技能导入相关
  {
    id: 'step_discovery',
    nameZh: '目录扫描',
    nameEn: 'Directory Discovery',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '目录',
    unitEn: 'dirs',
    taskTypes: ['add_skill'],
    descriptionZh: '遍历扫描 skills/ 插件目录结构与元数据文件',
    descriptionEn: 'Traverse and scan skills/ plugin directory structure and metadata',
  },
  {
    id: 'step_validation',
    nameZh: '规范校验',
    nameEn: 'Spec Validation',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '技能',
    unitEn: 'skills',
    taskTypes: ['add_skill'],
    descriptionZh: '校验 SKILL.md 的 YAML 头部合规性与执行指令完整性',
    descriptionEn: 'Validate YAML frontmatter compliance and action completeness in SKILL.md',
  },

  // 7-9: 会话归档相关
  {
    id: 'step_archival',
    nameZh: '对话归档',
    nameEn: 'Dialogue Archival',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '轮',
    unitEn: 'turns',
    taskTypes: ['session_commit'],
    descriptionZh: '提取 Agent 对话多轮历史，序列化上下文与消息流水',
    descriptionEn: 'Extract multi-turn dialogue history, serialize context and messages',
  },
  {
    id: 'step_lessons',
    nameZh: '经验萃取',
    nameEn: 'Lesson Extraction',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '条经验',
    unitEn: 'lessons',
    taskTypes: ['session_commit'],
    descriptionZh: '提炼对话中的工程教训、决策偏好并沉淀为记忆 Lessons',
    descriptionEn: 'Distill engineering lessons and decision preferences into memory lessons',
  },
  {
    id: 'step_snapshot',
    nameZh: '快照提交',
    nameEn: 'Snapshot Commit',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '快照',
    unitEn: 'commits',
    taskTypes: ['session_commit'],
    descriptionZh: '生成全局版本快照 Commit，确保跨会话持久化与可回滚',
    descriptionEn: 'Generate global snapshot commit ensuring persistence and rollback',
  },

  // 10-12: 全局索引重建
  {
    id: 'step_scan',
    nameZh: '语义提炼',
    nameEn: 'Semantic Generation',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['admin_reindex'],
    descriptionZh: '递归遍历并调用 LLM 生成知识库所有文件与目录的语义摘要 (.abstract.md / .overview.md)',
    descriptionEn: 'Recursively traverse and generate semantic summaries for all nodes',
  },
  {
    id: 'step_reconstruction',
    nameZh: '切片重构',
    nameEn: 'Chunk Reconstruction',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['admin_reindex'],
    descriptionZh: '按照最新 Embedding 模型超参数重新切块并计算全量向量',
    descriptionEn: 'Re-chunk and compute full vector embeddings using latest parameters',
  },
  {
    id: 'step_pruning',
    nameZh: '悬空修剪',
    nameEn: 'Orphan Pruning',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['admin_reindex'],
    descriptionZh: '清理已删除或断开关联的悬空切片与历史悬空记录（仅在指定修剪模式或检测到孤儿碎片时按需触发）',
    descriptionEn: 'Clean up orphaned chunks and dangling historical records',
  },

  // 13-15: 快照恢复重构
  {
    id: 'step_rollback',
    nameZh: '快照回滚',
    nameEn: 'Snapshot Rollback',
    engineKey: 'SessionCommit',
    engineNameZh: '会话归档',
    engineNameEn: 'Session Archival Engine',
    unitZh: '快照',
    unitEn: 'commits',
    taskTypes: ['snapshot_restore_reindex'],
    descriptionZh: '定位历史快照 Tag，安全回滚 AGFS 目录树状态',
    descriptionEn: 'Locate historical snapshot tag and safely rollback AGFS directory state',
  },
  {
    id: 'step_inodes',
    nameZh: '节点还原',
    nameEn: 'Inode Restoration',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'inodes',
    taskTypes: ['snapshot_restore_reindex'],
    descriptionZh: '重建快照中的 Inode 索引节点与属性元数据',
    descriptionEn: 'Rebuild Inode index nodes and attribute metadata from snapshot',
  },
  {
    id: 'step_incremental_vector',
    nameZh: '增量向量',
    nameEn: 'Incremental Embedding',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '切片',
    unitEn: 'chunks',
    taskTypes: ['snapshot_restore_reindex'],
    descriptionZh: '仅对差异变更的切片进行增量向量计算与补齐',
    descriptionEn: 'Compute incremental vector embeddings only for modified chunks',
  },

  // 16-17: 连接器导入
  {
    id: 'step_auth',
    nameZh: '连接鉴权',
    nameEn: 'Connector Auth',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '连接',
    unitEn: 'connections',
    taskTypes: ['connector_import'],
    descriptionZh: '校验飞书/Notion/GitHub/WebDAV 等外部源 Token 与凭证',
    descriptionEn: 'Validate external source tokens for Feishu, Notion, GitHub, WebDAV',
  },
  {
    id: 'step_fetch',
    nameZh: '资源拉取',
    nameEn: 'Remote Fetch',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '篇',
    unitEn: 'docs',
    taskTypes: ['connector_import'],
    descriptionZh: '从外部 API 批量拉取文档流与附件并缓冲至暂存区',
    descriptionEn: 'Batch fetch document streams and attachments from external APIs',
  },

  // 18-20: 旧数据迁移
  {
    id: 'step_read',
    nameZh: '数据读取',
    nameEn: 'Legacy Read',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '条',
    unitEn: 'records',
    taskTypes: ['legacy_migration'],
    descriptionZh: '兼容性加载旧版 V1/V2 数据库与历史元数据存储',
    descriptionEn: 'Backward-compatible loading of legacy V1/V2 database records',
  },
  {
    id: 'step_transform',
    nameZh: '格式转换',
    nameEn: 'Schema Transform',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '项',
    unitEn: 'items',
    taskTypes: ['legacy_migration'],
    descriptionZh: '将旧版 Schema 转换为 OpenViking 标准化 AGFS Schema',
    descriptionEn: 'Transform legacy schema into OpenViking standard AGFS schema',
  },
  {
    id: 'step_agfs_write',
    nameZh: '存储落盘',
    nameEn: 'Storage Persist',
    engineKey: 'AddResource',
    engineNameZh: '资源入库',
    engineNameEn: 'Resource Ingestion Engine',
    unitZh: '节点',
    unitEn: 'inodes',
    taskTypes: ['legacy_migration'],
    descriptionZh: '把迁移后的结构化数据原子写入 AGFS 文件系统并落盘',
    descriptionEn: 'Atomically write migrated structured data into AGFS tree',
  },

  // 21-23: 旧数据清理
  {
    id: 'step_traverse',
    nameZh: '图谱遍历',
    nameEn: 'Graph Traversal',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '实体',
    unitEn: 'entities',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '深度遍历知识图谱关联，标记所有活跃与失效引用链',
    descriptionEn: 'Deep traverse knowledge graph to mark active and stale references',
  },
  {
    id: 'step_gc',
    nameZh: '碎片回收',
    nameEn: 'Garbage Collection',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: '项',
    unitEn: 'items',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '执行垃圾回收 (GC) 算法，清除断链悬空实体与无效切片',
    descriptionEn: 'Garbage collection to purge dangling entities and stale chunks',
  },
  {
    id: 'step_free',
    nameZh: '空间释放',
    nameEn: 'Space Release',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Namespace Deletion Engine',
    unitZh: 'MB / 字节',
    unitEn: 'MB / bytes',
    taskTypes: ['legacy_cleanup'],
    descriptionZh: '物理释放磁盘占用，整理存储空间并更新配额',
    descriptionEn: 'Physically release disk storage and update namespace quotas',
  },

  // 24: 质量门禁与抗熵增质检
  {
    id: 'step_quality_gate',
    nameZh: '质量门禁',
    nameEn: 'Quality Gate',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '用例',
    unitEn: 'cases',
    taskTypes: ['quality_gate', 'benchmark_eval'],
    operators: ['QuerySample', 'VectorRetrieve', 'RagasJudge', 'MetricAssert'],
    descriptionZh: '执行 RAGAS 四维抗熵增质检（排布精度、覆盖率、忠实度、相关度），断言检索质量',
    descriptionEn: 'Execute RAGAS 4D anti-entropy evaluation verifying retrieval precision and health',
  },

  // 25-28: 记忆流与反思做梦 (Stanford Generative Agents)
  {
    id: 'step_scan_observations',
    nameZh: '观察扫描',
    nameEn: 'Scan Observations',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '条',
    unitEn: 'records',
    taskTypes: ['memory_dream'],
    descriptionZh: '扫描近期低抽象会话流水与原始日志，计算时效衰减与重要性积分',
    descriptionEn: 'Scan raw dialogue streams and calculate recency & importance scores',
  },
  {
    id: 'step_cluster_themes',
    nameZh: '模式聚类',
    nameEn: 'Cluster Themes',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '簇',
    unitEn: 'clusters',
    taskTypes: ['memory_dream'],
    descriptionZh: '对多条琐碎观察进行无监督语义聚类，收敛为核心模式主题',
    descriptionEn: 'Unsupervised clustering of observations into high-level themes',
  },
  {
    id: 'step_distill_insights',
    nameZh: '反思提炼',
    nameEn: 'Distill Insights',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '条',
    unitEn: 'insights',
    taskTypes: ['memory_dream'],
    descriptionZh: '驱动 LLM 深度反思，提炼高阶因果规律、认知洞察与永久准则',
    descriptionEn: 'Invoke LLM for deep reflection and distill high-level causal insights',
  },
  {
    id: 'step_consolidate_master',
    nameZh: '主记忆固化',
    nameEn: 'Consolidate Master',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['memory_dream'],
    descriptionZh: '将提炼洞察作为权威节点写回 Master Memory 并完成向量入脑',
    descriptionEn: 'Write insight nodes into Master Memory and embed into vector index',
  },

  // 29-32: 分层内存与压缩淘汰 (MemGPT / Letta)
  {
    id: 'step_evaluate_tiers',
    nameZh: '分层体检',
    nameEn: 'Evaluate Tiers',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '条',
    unitEn: 'records',
    taskTypes: ['memory_compaction'],
    descriptionZh: '依据 access_count 与最后访问时间，执行 Hot/Warm/Cold 自动分层',
    descriptionEn: 'Evaluate access frequency and recency for Hot/Warm/Cold tiering',
  },
  {
    id: 'step_cosine_deduplication',
    nameZh: '余弦去重',
    nameEn: 'Cosine Dedup',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '对',
    unitEn: 'pairs',
    taskTypes: ['memory_compaction'],
    descriptionZh: '余弦相似度高阈值 (>0.92) 重复项检测与淘汰标记',
    descriptionEn: 'Cosine similarity high-threshold (>0.92) redundancy detection',
  },
  {
    id: 'step_prune_and_archive',
    nameZh: '剪枝归档',
    nameEn: 'Prune & Archive',
    engineKey: 'UserDeletion',
    engineNameZh: '空间注销',
    engineNameEn: 'Space Purge Engine',
    unitZh: '条',
    unitEn: 'items',
    taskTypes: ['memory_compaction'],
    descriptionZh: '按艾宾浩斯半衰期淘汰低价值碎屑，超额记忆归档至冷存',
    descriptionEn: 'Prune decayed fragments and archive overflow memories to cold storage',
  },
  {
    id: 'step_rebalance_index',
    nameZh: '索引重平衡',
    nameEn: 'Rebalance Index',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '簇心',
    unitEn: 'centroids',
    taskTypes: ['memory_compaction'],
    descriptionZh: '重新计算向量聚类中心，消除空洞与向量空间拥挤',
    descriptionEn: 'Recompute vector centroids to eliminate fragmentation and crowding',
  },

  // 33-36: 增量事实与四态流转 (Mem0 / AutoGen)
  {
    id: 'step_extract_atomic_facts',
    nameZh: '原子事实抽取',
    nameEn: 'Extract Facts',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '事实',
    unitEn: 'facts',
    taskTypes: ['fact_mutation'],
    descriptionZh: '将非结构化文档或对话拆解为高精度独立原子事实断言',
    descriptionEn: 'Decompose source text into atomic independent factual assertions',
  },
  {
    id: 'step_semantic_conflict_check',
    nameZh: '冲突检测',
    nameEn: 'Conflict Check',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '断言',
    unitEn: 'assertions',
    taskTypes: ['fact_mutation'],
    descriptionZh: '与现有事实图谱对比，检测语义重叠、演变与事实自相矛盾',
    descriptionEn: 'Compare against existing graph to detect overlaps and contradictions',
  },
  {
    id: 'step_execute_4way_mutation',
    nameZh: '四态流转',
    nameEn: '4-Way Mutation',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '动作',
    unitEn: 'actions',
    taskTypes: ['fact_mutation'],
    descriptionZh: '执行 ADD(增)/UPDATE(变)/DELETE(废)/NOOP(略) 四态决策分流',
    descriptionEn: 'Execute ADD/UPDATE/DELETE/NOOP 4-way mutation routing at ingestion gate',
  },
  {
    id: 'step_commit_knowledge_graph',
    nameZh: '图谱原子提交',
    nameEn: 'Commit Graph',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '事实',
    unitEn: 'facts',
    taskTypes: ['fact_mutation'],
    descriptionZh: '将事实变更原子提交至图谱与向量索引，入口阻断信息熵增',
    descriptionEn: 'Atomically commit fact changes to graph and vector index',
  },

  // 37-40: 时态图谱与实体浓缩 (Zep)
  {
    id: 'step_extract_entities_relations',
    nameZh: '实体关系抽取',
    nameEn: 'Entity Relations',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '三元组',
    unitEn: 'triples',
    taskTypes: ['entity_summarization'],
    descriptionZh: '提取实体、属性、事件与因果拓扑三元组',
    descriptionEn: 'Extract entity-attribute-event causal topology triples',
  },
  {
    id: 'step_temporal_timeline_ordering',
    nameZh: '时序排序',
    nameEn: 'Timeline Ordering',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '事件',
    unitEn: 'events',
    taskTypes: ['entity_summarization'],
    descriptionZh: '沿时间轴对实体变更事件建立有序版本演进链',
    descriptionEn: 'Order entity evolution events along chronological timeline',
  },
  {
    id: 'step_merge_temporal_contradictions',
    nameZh: '时序矛盾消解',
    nameEn: 'Resolve Contradictions',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '冲突',
    unitEn: 'conflicts',
    taskTypes: ['entity_summarization'],
    descriptionZh: '消解历史先后冲突，提纯当前时刻权威事实 (Current Truth)',
    descriptionEn: 'Resolve temporal contradictions and distill current authoritative state',
  },
  {
    id: 'step_update_entity_index',
    nameZh: '实体浓缩更新',
    nameEn: 'Update Entity SSOT',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '实体',
    unitEn: 'entities',
    taskTypes: ['entity_summarization'],
    descriptionZh: '更新实体单一真相源 (SSOT) 浓缩文档与关联向量',
    descriptionEn: 'Update entity single source of truth summary document and vectors',
  },

  // 41-44: 四层治理与同主题合并 (Home Project Baseline)
  {
    id: 'step_tier_diagnosis',
    nameZh: '四层全息诊断',
    nameEn: 'Four-Tier Diagnosis',
    engineKey: 'Semantic',
    engineNameZh: '语义分析',
    engineNameEn: 'Semantic Engine',
    unitZh: '维度',
    unitEn: 'tiers',
    taskTypes: ['four_tier_governance'],
    descriptionZh: '数量层、质量层、结构层、查询层全息健康度体检',
    descriptionEn: 'Diagnosis across quantity, quality, structure, and query tiers',
  },
  {
    id: 'step_topic_grouping',
    nameZh: '同主题聚类',
    nameEn: 'Topic Grouping',
    engineKey: 'Semantic-Nodes',
    engineNameZh: '语义拓扑',
    engineNameEn: 'Semantic Topology Engine',
    unitZh: '主题',
    unitEn: 'topics',
    taskTypes: ['four_tier_governance'],
    descriptionZh: '将散落在不同文档和历史会话中的同主题零散笔记聚类合并',
    descriptionEn: 'Group scattered topic fragments across documents and conversations',
  },
  {
    id: 'step_llm_topic_synthesis',
    nameZh: '主题深度归纳',
    nameEn: 'Topic Synthesis',
    engineKey: 'Semantic',
    engineNameZh: '语义提取',
    engineNameEn: 'Semantic Extraction Engine',
    unitZh: '篇',
    unitEn: 'docs',
    taskTypes: ['four_tier_governance'],
    descriptionZh: '驱动 LLM 深度整合同主题笔记，剔除重复，提纯为结构化统一纲要',
    descriptionEn: 'Invoke LLM to synthesize topic notes into a clean structural outline',
  },
  {
    id: 'step_writeback_and_cleanup',
    nameZh: '纲要写回与清理',
    nameEn: 'Writeback & Clean',
    engineKey: 'Embedding',
    engineNameZh: '向量计算',
    engineNameEn: 'Vector Embedding Engine',
    unitZh: '节点',
    unitEn: 'nodes',
    taskTypes: ['four_tier_governance'],
    descriptionZh: '结构化合并产物落盘写回，重构向量并软删除分散过时碎片',
    descriptionEn: 'Persist consolidated outline, reindex vectors, soft-delete fragments',
  },
]

export interface TaskTypeFlowDef {
  typeKey: string
  nameZh: string
  nameEn: string
  stepIds: string[]
}

export const TASK_FLOWS: TaskTypeFlowDef[] = [
  {
    typeKey: 'add_resource',
    nameZh: '资源处理',
    nameEn: 'Resource Ingestion',
    stepIds: ['step_ingestion', 'step_parse', 'step_semantic', 'step_embedding', 'step_memory_linking'],
  },
  {
    typeKey: 'add_skill',
    nameZh: '技能导入',
    nameEn: 'Skill Discovery',
    stepIds: ['step_discovery', 'step_validation', 'step_embedding'],
  },
  {
    typeKey: 'session_commit',
    nameZh: '会话提交',
    nameEn: 'Session Commit',
    stepIds: ['step_archival', 'step_lessons', 'step_snapshot'],
  },
  {
    typeKey: 'admin_reindex',
    nameZh: '全局索引重建',
    nameEn: 'Global Reindex',
    stepIds: ['step_scan', 'step_reconstruction', 'step_pruning'],
  },
  {
    typeKey: 'snapshot_restore_reindex',
    nameZh: '快照恢复索引',
    nameEn: 'Snapshot Restore',
    stepIds: ['step_rollback', 'step_inodes', 'step_incremental_vector'],
  },
  {
    typeKey: 'connector_import',
    nameZh: '连接器导入',
    nameEn: 'Connector Import',
    stepIds: ['step_auth', 'step_fetch', 'step_parse', 'step_semantic', 'step_embedding'],
  },
  {
    typeKey: 'legacy_migration',
    nameZh: '旧数据迁移',
    nameEn: 'Legacy Migration',
    stepIds: ['step_read', 'step_transform', 'step_agfs_write'],
  },
  {
    typeKey: 'legacy_cleanup',
    nameZh: '旧数据清理',
    nameEn: 'Legacy Cleanup',
    stepIds: ['step_traverse', 'step_gc', 'step_free'],
  },
  { typeKey: 'quality_gate', nameZh: '质量门禁', nameEn: 'Quality Gate', stepIds: ['step_quality_gate'] },
  { typeKey: 'benchmark_eval', nameZh: '基准质检', nameEn: 'Benchmark Evaluation', stepIds: ['step_quality_gate'] },
  { typeKey: 'knowledge_remediation', nameZh: '知识自愈优化', nameEn: 'Knowledge Remediation', stepIds: ['step_fault_locate', 'step_conflict_arbitrate', 'step_targeted_distill', 'step_delta_reindex'] },
  { typeKey: 'memory_dream', nameZh: '记忆流反思做梦', nameEn: 'Memory Stream & Reflection', stepIds: ['step_scan_observations', 'step_cluster_themes', 'step_distill_insights', 'step_consolidate_master'] },
  { typeKey: 'memory_compaction', nameZh: '分层内存压缩淘汰', nameEn: 'Hierarchical Compaction', stepIds: ['step_evaluate_tiers', 'step_cosine_deduplication', 'step_prune_and_archive', 'step_rebalance_index'] },
  { typeKey: 'fact_mutation', nameZh: '增量事实四态流转', nameEn: 'Fact 4-Way Mutation', stepIds: ['step_extract_atomic_facts', 'step_semantic_conflict_check', 'step_execute_4way_mutation', 'step_commit_knowledge_graph'] },
  { typeKey: 'entity_summarization', nameZh: '时态图谱实体浓缩', nameEn: 'Entity Summarization', stepIds: ['step_extract_entities_relations', 'step_temporal_timeline_ordering', 'step_merge_temporal_contradictions', 'step_update_entity_index'] },
  { typeKey: 'four_tier_governance', nameZh: '四层治理同主题合并', nameEn: 'Four-Tier Governance', stepIds: ['step_tier_diagnosis', 'step_topic_grouping', 'step_llm_topic_synthesis', 'step_writeback_and_cleanup'] },
]
