import type { AtomicStepSpec } from './task-pipeline-schema'

/**
 * 抗熵增五大范式流水线工序元数据 (Anti-Entropy Step Specs 29-48)
 * 涵盖 Stanford Reflection, MemGPT Compaction, Mem0 Mutation, Zep Entity, Four-Tier Governance
 */
export const ENTROPY_STEP_SPECS: Record<string, AtomicStepSpec> = {
  // 29-32: 记忆流与反思做梦 (Stanford Generative Agents)
  step_scan_observations: {
    id: 'step_scan_observations',
    nameZh: '观察扫描',
    nameEn: 'Scan Observations',
    unitZh: '条',
    unitEn: 'records',
    stageKeywords: ['scan', 'observe', 'observation'],
    metricKeys: ['raw_observations_count', 'scanned_records', 'observations_count'],
    engineKey: 'semantic',
  },
  step_cluster_themes: {
    id: 'step_cluster_themes',
    nameZh: '模式聚类',
    nameEn: 'Cluster Themes',
    unitZh: '簇',
    unitEn: 'clusters',
    stageKeywords: ['cluster', 'theme', 'pattern'],
    metricKeys: ['clusters_count', 'themes_count'],
    engineKey: 'semantic_nodes',
  },
  step_distill_insights: {
    id: 'step_distill_insights',
    nameZh: '反思提炼',
    nameEn: 'Distill Insights',
    unitZh: '条',
    unitEn: 'insights',
    stageKeywords: ['distill', 'insight', 'reflect', 'reflection'],
    metricKeys: ['distilled_insights_count', 'insights_extracted', 'insights_count'],
    engineKey: 'semantic',
  },
  step_consolidate_master: {
    id: 'step_consolidate_master',
    nameZh: '主记忆固化',
    nameEn: 'Consolidate Master',
    unitZh: '节点',
    unitEn: 'nodes',
    stageKeywords: ['consolidate', 'master', 'save', 'write'],
    metricKeys: ['saved_nodes', 'written_nodes', 'insights_extracted'],
    engineKey: 'embedding',
  },

  // 33-36: 分层内存与压缩淘汰 (MemGPT / Letta)
  step_evaluate_tiers: {
    id: 'step_evaluate_tiers',
    nameZh: '分层体检',
    nameEn: 'Evaluate Tiers',
    unitZh: '条',
    unitEn: 'records',
    stageKeywords: ['tier', 'evaluate', 'scan'],
    metricKeys: ['scanned_records', 'total_records', 'hot_count'],
    engineKey: 'semantic',
  },
  step_cosine_deduplication: {
    id: 'step_cosine_deduplication',
    nameZh: '余弦去重',
    nameEn: 'Cosine Dedup',
    unitZh: '对',
    unitEn: 'pairs',
    stageKeywords: ['cosine', 'dedup', 'similarity'],
    metricKeys: ['pruned_duplicates', 'duplicate_pairs'],
    engineKey: 'embedding',
  },
  step_prune_and_archive: {
    id: 'step_prune_and_archive',
    nameZh: '剪枝归档',
    nameEn: 'Prune & Archive',
    unitZh: '条',
    unitEn: 'items',
    stageKeywords: ['prune', 'archive', 'decay'],
    metricKeys: ['decayed_records', 'archived_records', 'pruned_duplicates'],
    engineKey: 'user_deletion',
  },
  step_rebalance_index: {
    id: 'step_rebalance_index',
    nameZh: '索引重平衡',
    nameEn: 'Rebalance Index',
    unitZh: '簇心',
    unitEn: 'centroids',
    stageKeywords: ['rebalance', 'index', 'cluster'],
    metricKeys: ['rebalanced_centroids', 'updated_centroids'],
    isActionOnly: true,
    engineKey: 'embedding',
  },

  // 37-40: 增量事实与四态流转 (Mem0 / AutoGen)
  step_extract_atomic_facts: {
    id: 'step_extract_atomic_facts',
    nameZh: '原子事实抽取',
    nameEn: 'Extract Facts',
    unitZh: '事实',
    unitEn: 'facts',
    stageKeywords: ['extract', 'fact', 'atomic'],
    metricKeys: ['extracted_facts', 'facts_count'],
    engineKey: 'semantic',
  },
  step_semantic_conflict_check: {
    id: 'step_semantic_conflict_check',
    nameZh: '冲突检测',
    nameEn: 'Conflict Check',
    unitZh: '断言',
    unitEn: 'assertions',
    stageKeywords: ['conflict', 'check', 'overlap'],
    metricKeys: ['conflicts_resolved', 'resolved_conflicts'],
    engineKey: 'semantic_nodes',
  },
  step_execute_4way_mutation: {
    id: 'step_execute_4way_mutation',
    nameZh: '四态流转执行',
    nameEn: '4-Way Mutation',
    unitZh: '条',
    unitEn: 'mutations',
    stageKeywords: ['mutation', 'execute', '4way', 'dispatch'],
    metricKeys: ['add_count', 'net_new_facts'],
    engineKey: 'viking_write',
  },
  step_commit_knowledge_graph: {
    id: 'step_commit_knowledge_graph',
    nameZh: '图谱原子提交',
    nameEn: 'Commit Graph',
    unitZh: '三元组',
    unitEn: 'triples',
    stageKeywords: ['commit', 'graph', 'topology'],
    metricKeys: ['net_new_facts', 'committed_triples'],
    engineKey: 'viking_write',
  },

  // 41-44: 时态图谱与实体浓缩 (Zep)
  step_extract_entities_relations: {
    id: 'step_extract_entities_relations',
    nameZh: '实体三元组抽取',
    nameEn: 'Extract Entities',
    unitZh: '实体',
    unitEn: 'entities',
    stageKeywords: ['extract', 'entity', 'entities', 'relation'],
    metricKeys: ['timeline_events_count', 'extracted_entities'],
    engineKey: 'semantic',
  },
  step_temporal_timeline_ordering: {
    id: 'step_temporal_timeline_ordering',
    nameZh: '时序版本链排序',
    nameEn: 'Timeline Ordering',
    unitZh: '事件',
    unitEn: 'events',
    stageKeywords: ['timeline', 'order', 'temporal'],
    metricKeys: ['timeline_events_count'],
    engineKey: 'semantic_nodes',
  },
  step_merge_temporal_contradictions: {
    id: 'step_merge_temporal_contradictions',
    nameZh: '时序矛盾消解',
    nameEn: 'Merge Contradictions',
    unitZh: '冲突',
    unitEn: 'contradictions',
    stageKeywords: ['contradiction', 'merge', 'resolve'],
    metricKeys: ['resolved_contradictions'],
    engineKey: 'semantic',
  },
  step_update_entity_index: {
    id: 'step_update_entity_index',
    nameZh: '实体SSOT浓缩更新',
    nameEn: 'Update Entity SSOT',
    unitZh: '节点',
    unitEn: 'nodes',
    stageKeywords: ['update', 'ssot', 'canonical'],
    isActionOnly: true,
    engineKey: 'embedding',
  },

  // 45-48: 四层全息治理 (项目工程基线)
  step_tier_diagnosis: {
    id: 'step_tier_diagnosis',
    nameZh: '四层全息诊断',
    nameEn: 'Tier Diagnosis',
    unitZh: '维度',
    unitEn: 'tiers',
    stageKeywords: ['diagnosis', 'tier', 'assess'],
    metricKeys: ['governed_tiers_count'],
    engineKey: 'semantic',
  },
  step_topic_grouping: {
    id: 'step_topic_grouping',
    nameZh: '同主题聚类',
    nameEn: 'Topic Grouping',
    unitZh: '篇',
    unitEn: 'notes',
    stageKeywords: ['group', 'topic', 'cluster'],
    metricKeys: ['merged_notes_count'],
    engineKey: 'semantic_nodes',
  },
  step_llm_topic_synthesis: {
    id: 'step_llm_topic_synthesis',
    nameZh: '同主题深度归纳',
    nameEn: 'Topic Synthesis',
    unitZh: '纲要',
    unitEn: 'outlines',
    stageKeywords: ['synthesis', 'synthesize', 'summarize', 'llm'],
    metricKeys: ['synthesized_outlines'],
    engineKey: 'semantic',
  },
  step_writeback_and_cleanup: {
    id: 'step_writeback_and_cleanup',
    nameZh: '纲要写回与清理',
    nameEn: 'Writeback & Clean',
    unitZh: '节点',
    unitEn: 'nodes',
    stageKeywords: ['writeback', 'clean', 'cleanup'],
    isActionOnly: true,
    engineKey: 'embedding',
  },
}
