/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphRouteRouteImport } from './routes/graph/route'
import { Route as HarnessLogsRouteImport } from './routes/harness-logs'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as MonitoringRouteRouteImport } from './routes/monitoring/route'
import { Route as PlaygroundRouteRouteImport } from './routes/playground/route'
import { Route as RequestLogsRouteRouteImport } from './routes/request-logs/route'
import { Route as ResourcesRouteRouteImport } from './routes/resources/route'
import { Route as RetrievalRouteRouteImport } from './routes/retrieval/route'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SkillsRouteRouteImport } from './routes/skills/route'
import { Route as TasksRouteRouteImport } from './routes/tasks/route'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as OauthVerifyRouteImport } from './routes/oauth/verify'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SkillsHarnessLogsRouteImport } from './routes/skills/harness-logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRouteRoute = GraphRouteRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HarnessLogsRoute = HarnessLogsRouteImport.update({
  id: '/harness-logs',
  path: '/harness-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRouteRoute = MonitoringRouteRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRouteRoute = PlaygroundRouteRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestLogsRouteRoute = RequestLogsRouteRouteImport.update({
  id: '/request-logs',
  path: '/request-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRouteRoute = ResourcesRouteRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrievalRouteRoute = RetrievalRouteRouteImport.update({
  id: '/retrieval',
  path: '/retrieval',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRouteRoute = SkillsRouteRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRouteRoute = TasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthVerifyRoute = OauthVerifyRouteImport.update({
  id: '/oauth/verify',
  path: '/oauth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SkillsHarnessLogsRoute = SkillsHarnessLogsRouteImport.update({
  id: '/harness-logs',
  path: '/harness-logs',
  getParentRoute: () => SkillsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRouteRoute
  '/home': typeof HomeRouteRoute
  '/monitoring': typeof MonitoringRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/request-logs': typeof RequestLogsRouteRoute
  '/resources': typeof ResourcesRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/skills': typeof SkillsRouteRouteWithChildren
  '/tasks': typeof TasksRouteRoute
  '/users': typeof UsersRouteRoute
  '/harness-logs': typeof HarnessLogsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/skills/harness-logs': typeof SkillsHarnessLogsRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRouteRoute
  '/home': typeof HomeRouteRoute
  '/monitoring': typeof MonitoringRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/request-logs': typeof RequestLogsRouteRoute
  '/resources': typeof ResourcesRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/skills': typeof SkillsRouteRouteWithChildren
  '/tasks': typeof TasksRouteRoute
  '/users': typeof UsersRouteRoute
  '/harness-logs': typeof HarnessLogsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/skills/harness-logs': typeof SkillsHarnessLogsRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRouteRoute
  '/home': typeof HomeRouteRoute
  '/monitoring': typeof MonitoringRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/request-logs': typeof RequestLogsRouteRoute
  '/resources': typeof ResourcesRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/skills': typeof SkillsRouteRouteWithChildren
  '/tasks': typeof TasksRouteRoute
  '/users': typeof UsersRouteRoute
  '/harness-logs': typeof HarnessLogsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/skills/harness-logs': typeof SkillsHarnessLogsRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/home'
    | '/monitoring'
    | '/playground'
    | '/request-logs'
    | '/resources'
    | '/retrieval'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/users'
    | '/harness-logs'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/skills/harness-logs'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/home'
    | '/monitoring'
    | '/playground'
    | '/request-logs'
    | '/resources'
    | '/retrieval'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/users'
    | '/harness-logs'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/skills/harness-logs'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/home'
    | '/monitoring'
    | '/playground'
    | '/request-logs'
    | '/resources'
    | '/retrieval'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/users'
    | '/harness-logs'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/skills/harness-logs'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRouteRoute: typeof GraphRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
  MonitoringRouteRoute: typeof MonitoringRouteRoute
  PlaygroundRouteRoute: typeof PlaygroundRouteRoute
  RequestLogsRouteRoute: typeof RequestLogsRouteRoute
  ResourcesRouteRoute: typeof ResourcesRouteRoute
  RetrievalRouteRoute: typeof RetrievalRouteRoute
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRoute
  SkillsRouteRoute: typeof SkillsRouteRouteWithChildren
  TasksRouteRoute: typeof TasksRouteRoute
  UsersRouteRoute: typeof UsersRouteRoute
  HarnessLogsRoute: typeof HarnessLogsRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthVerifyRoute: typeof OauthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-logs': {
      id: '/harness-logs'
      path: '/harness-logs'
      fullPath: '/harness-logs'
      preLoaderRoute: typeof HarnessLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-logs': {
      id: '/request-logs'
      path: '/request-logs'
      fullPath: '/request-logs'
      preLoaderRoute: typeof RequestLogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieval': {
      id: '/retrieval'
      path: '/retrieval'
      fullPath: '/retrieval'
      preLoaderRoute: typeof RetrievalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/verify': {
      id: '/oauth/verify'
      path: '/oauth/verify'
      fullPath: '/oauth/verify'
      preLoaderRoute: typeof OauthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/skills/harness-logs': {
      id: '/skills/harness-logs'
      path: '/harness-logs'
      fullPath: '/skills/harness-logs'
      preLoaderRoute: typeof SkillsHarnessLogsRouteImport
      parentRoute: typeof SkillsRouteRoute
    }
  }
}

interface SessionsRouteRouteChildren {
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

interface SkillsRouteRouteChildren {
  SkillsHarnessLogsRoute: typeof SkillsHarnessLogsRoute
}

const SkillsRouteRouteChildren: SkillsRouteRouteChildren = {
  SkillsHarnessLogsRoute: SkillsHarnessLogsRoute,
}

const SkillsRouteRouteWithChildren = SkillsRouteRoute._addFileChildren(
  SkillsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRouteRoute: GraphRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
  MonitoringRouteRoute: MonitoringRouteRoute,
  PlaygroundRouteRoute: PlaygroundRouteRoute,
  RequestLogsRouteRoute: RequestLogsRouteRoute,
  ResourcesRouteRoute: ResourcesRouteRoute,
  RetrievalRouteRoute: RetrievalRouteRoute,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRoute,
  SkillsRouteRoute: SkillsRouteRouteWithChildren,
  TasksRouteRoute: TasksRouteRoute,
  UsersRouteRoute: UsersRouteRoute,
  HarnessLogsRoute: HarnessLogsRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthVerifyRoute: OauthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
